version: "3"
services:
    api:
        container_name: sw-planets-api
        build: .
        restart: unless-stopped
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
            - "9229:9229" #para debugar de dentro do docker, mas tem que rebuildar sem a flag de produção
        depends_on:
            - mongo
        command: "npm start"

    mongo:
        image: mongo
        volumes:
            - db_volume:/data/db
volumes:
    db_volume:
